In [1]:
import pandas as pd

In [2]:
!nvidia-smi

"nvidia-smi" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
data_path = "./data/gestores_junio 2025.xlsx"

In [7]:
df = pd.read_excel(data_path, sheet_name="Registros de PI", engine="openpyxl")

In [8]:
df.head()

,N °,AÑO,Tipo de aplicación de propiedad intelectual (Secreto empresarial/ Diseño Industrial/ Marca/ Derecho de autor),Categoría,Categoría (marcas),Unnamed: 5,Nombre del registro,Centro de investigación/ Unidad académica,Descripción,TRL,Investigadores involucrados,CI. / PASAPORTE,Cant. Mujeres involucradas,Titular,Estado,Fecha de solicitud,Fecha de registro,Registro SENADI (Sí/No),"COD/No. Certificado (SENADI/NOTARIA, ETC)",Fecha de solicitud (Patente),Fecha de caducidad,Sector Productivo de impacto,Area de conocimiento,Tiene Transferencia Tecnológica? (Sí / No),Nombre del Proyecto Asociado,Comentarios,TRL.1,HOJA DE RUTA,ODS
0,1,2018,SECRETO EMPRESARIAL,SECRETO EMPRESARIAL,NaN,NaN,Desarrollo de Extracción de Proteínas de Choch...,CIBE,NaN,NaN,NaN,NaN,NaN,Ecopacific,Trasferido,NaN,2018-12-20 00:00:00,NaN,NaN,NaT,NaN,Agroindustrial,"Salud, bienestar y desarrollo humano",NaN,NaN,Secreto registrado y transferido de forma excl...,NaN,NaN,2
1,2,2018,SECRETO EMPRESARIAL,SECRETO EMPRESARIAL,NaN,NaN,Recubrimiento para Alimentos,FIMCP,NaN,NaN,Sandra Acosta,NaN,1,ESPOL,Registrado,NaN,NaN,NaN,NaN,NaT,NaN,Alimentos,"Industria sostenible e innovadora / Salud, bie...",NaN,NaN,NaN,NaN,NaN,"2,3"
2,3,2019,SECRETO EMPRESARIAL,SECRETO EMPRESARIAL,NaN,NaN,Reconocimiento de patrones en la aculcutura bl...,CIDIS,Sistema de monitoreo para parámetros del agua ...,4.0,"Equipo Blue Sensor, Boris Vintimilla",NaN,NaN,ESPOL,Trasferido,NaN,2019-06-04 00:00:00,NaN,NaN,NaT,NaN,Tecnologias Digitales,Ingenieria y Tecnologia,NaN,NaN,Se realizo el contrato de transferencia tecnol...,NaN,NaN,4
3,4,2019,SECRETO EMPRESARIAL,SECRETO EMPRESARIAL,NaN,NaN,Producto mircoencapsulado de plantas ilex guay...,CIBE,NaN,NaN,NaN,NaN,NaN,ESPOL,Registrado,NaN,2019-06-04 00:00:00,NaN,NaN,NaT,NaN,Agricultura,"Salud, bienestar y desarrollo humano",NaN,NaN,NaN,NaN,NaN,2
4,5,2019,SECRETO EMPRESARIAL,SECRETO EMPRESARIAL,NaN,NaN,Material compuesto de poliisocianurato-cascari...,CIBE,NaN,NaN,NaN,NaN,NaN,ESPOL,Registrado,NaN,2019-06-04 00:00:00,NaN,NaN,NaT,NaN,Agricultura,Ingenieria y Tecnologia,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 29 columns):
 #   Column                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                         --------------  -----
 0   N °                                                                                                            164 non-null    int64
 1   AÑO                                                                                                            164 non-null    int64
 2   Tipo de aplicación de propiedad intelectual (Secreto empresarial/ Diseño Industrial/ Marca/ Derecho de autor)  164 non-null    object
 3   Categoría                                                                                                      162 non-null    object
 4   Categoría (marcas)                                                                                             4 non-null      object
 5   Unnamed: 5                                                                                                     0 non-null      float64
 6   Nombre del registro                                                                                            164 non-null    object
 7   Centro de investigación/ Unidad académica                                                                      163 non-null    object
 8   Descripción                                                                                                    87 non-null     object
 9   TRL                                                                                                            2 non-null      float64
 10  Investigadores involucrados                                                                                    82 non-null     object
 11  CI. / PASAPORTE                                                                                                4 non-null      object
 12  Cant. Mujeres involucradas                                                                                     65 non-null     object
 13  Titular                                                                                                        149 non-null    object
 14  Estado                                                                                                         152 non-null    object
 15  Fecha de solicitud                                                                                             47 non-null     object
 16  Fecha de registro                                                                                              111 non-null    object
 17  Registro SENADI  (Sí/No)                                                                                       70 non-null     object
 18  COD/No. Certificado (SENADI/NOTARIA, ETC)                                                                      71 non-null     object
 19  Fecha de solicitud (Patente)                                                                                   3 non-null      datetime64[ns]
 20  Fecha de caducidad                                                                                             10 non-null     object
 21  Sector Productivo de impacto                                                                                   98 non-null     object
 22  Area de conocimiento                                                                                           77 non-null     object
 23  Tiene Transferencia Tecnológica? (Sí / No)                                                                     15 non-null     object
 24  Nombre del Proyecto Asociado                                                                                   7 non-null      object
 25  Comentarios                                                                                                    51 non-null     object
 26  TRL.1                                                                                                          0 non-null      float64
 27  HOJA DE RUTA                                                                                                   0 non-null      float64
 28  ODS                                                                                                            41 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(2), object(22)
memory usage: 37.3+ KB

In [ ]:
# obtener la columna 3
columna_3 = df.iloc[:, 2]  # Usando iloc para obtener la tercera columna

In [19]:
columna_3.value_counts()

Tipo de aplicación de propiedad intelectual (Secreto empresarial/ Diseño Industrial/ Marca/ Derecho de autor)
DERECHO DE AUTOR       51
MARCA                  48
SECRETO EMPRESARIAL    43
DISEÑO INDUSTRIAL      12
PATENTE                 8
LEMA COMERCIAL          2
Name: count, dtype: int64

In [14]:
df["Categoría"].value_counts()

Categoría
MARCA                           48
SECRETO EMPRESARIAL             43
OBRAS ARTISTICAS Y MUSICALES    29
DISEÑO INDUSTRIAL               12
OBRA LITERARIA                  10
SOFTWARE                         7
PATENTE PCT                      3
Patente PCT                      2
DERECHO DE AUTOR                 2
LEMA COMERCIAL                   2
PATENTE                          1
PATENTE ECUADOR                  1
Obra literaria                   1
PATENTE ESPAÑOLA                 1
Name: count, dtype: int64

In [32]:
df.iloc[:, [2, 3]].groupby("Categoría").size().reset_index(name='Count')

                       Categoría  Count
0               DERECHO DE AUTOR      2
1              DISEÑO INDUSTRIAL     12
2                 LEMA COMERCIAL      2
3                          MARCA     48
4                 OBRA LITERARIA     10
5   OBRAS ARTISTICAS Y MUSICALES     29
6                 Obra literaria      1
7                        PATENTE      1
8                PATENTE ECUADOR      1
9               PATENTE ESPAÑOLA      1
10                   PATENTE PCT      3
11                   Patente PCT      2
12           SECRETO EMPRESARIAL     43
13                      SOFTWARE      7

In [33]:
# contabilizar cuantas de la columna 4 (Categoría), se tiene de la columna 3 con iloc. Y que me muestre el valor de la columna 3 y el valor de la 4 y cuantos de la columna 4 hay de cada uno de la columna 3
# Acceder a las columnas usando iloc
columna_3 = df.iloc[:, 2]  # Columna 3 (índice 2)
columna_4 = df.iloc[:, 3]  # Columna 4 (índice 3)

# Crear un DataFrame temporal con las dos columnas
temp_df = pd.DataFrame({
    'columna_3': columna_3,
    'categoria': columna_4
})

# Contabilizar las combinaciones
conteo = temp_df.groupby(['columna_3', 'categoria']).size().reset_index(name='Cantidad')

In [35]:
print("Conteo de Columna 4 por cada valor de Columna 3:")
conteo

Conteo de Columna 4 por cada valor de Columna 3:

              columna_3                     categoria  Cantidad
0      DERECHO DE AUTOR              DERECHO DE AUTOR         2
1      DERECHO DE AUTOR                OBRA LITERARIA        10
2      DERECHO DE AUTOR  OBRAS ARTISTICAS Y MUSICALES        29
3      DERECHO DE AUTOR                Obra literaria         1
4      DERECHO DE AUTOR                      SOFTWARE         7
5     DISEÑO INDUSTRIAL             DISEÑO INDUSTRIAL        12
6        LEMA COMERCIAL                LEMA COMERCIAL         2
7                 MARCA                         MARCA        48
8               PATENTE                       PATENTE         1
9               PATENTE               PATENTE ECUADOR         1
10              PATENTE              PATENTE ESPAÑOLA         1
11              PATENTE                   PATENTE PCT         3
12              PATENTE                   Patente PCT         2
13  SECRETO EMPRESARIAL           SECRETO EMPRESARIAL        43

In [37]:
# También puedes ver un resumen por columna 3
resumen_por_col3 = temp_df.groupby('columna_3')['categoria'].value_counts().reset_index(name='Cantidad')
print("\nResumen detallado:")
resumen_por_col3

Resumen detallado:

              columna_3                     categoria  Cantidad
0      DERECHO DE AUTOR  OBRAS ARTISTICAS Y MUSICALES        29
1      DERECHO DE AUTOR                OBRA LITERARIA        10
2      DERECHO DE AUTOR                      SOFTWARE         7
3      DERECHO DE AUTOR              DERECHO DE AUTOR         2
4      DERECHO DE AUTOR                Obra literaria         1
5     DISEÑO INDUSTRIAL             DISEÑO INDUSTRIAL        12
6        LEMA COMERCIAL                LEMA COMERCIAL         2
7                 MARCA                         MARCA        48
8               PATENTE                   PATENTE PCT         3
9               PATENTE                   Patente PCT         2
10              PATENTE                       PATENTE         1
11              PATENTE               PATENTE ECUADOR         1
12              PATENTE              PATENTE ESPAÑOLA         1
13  SECRETO EMPRESARIAL           SECRETO EMPRESARIAL        43

In [38]:
# Para ver el total por cada valor de columna 3
total_por_col3 = temp_df.groupby('columna_3').size().reset_index(name='Total')
print("\nTotal por Columna 3:")
total_por_col3

Total por Columna 3:

             columna_3  Total
0     DERECHO DE AUTOR     51
1    DISEÑO INDUSTRIAL     12
2       LEMA COMERCIAL      2
3                MARCA     48
4              PATENTE      8
5  SECRETO EMPRESARIAL     43